
export const IMAGE_COMPONENTS = {
    logo: require("../../assets/images/icon.png"),
    homeLogo: require("../../assets/images/homeLogo.png"),
    emailImage: require("../../assets/images/emailImage.png"),
    welcomeImage: require("../../assets/images/welcomeImage.png"),
    hostWelcomeImage: require("../../assets/images/hostWelcome.png"),
    cleanerWelcomeImage: require("../../assets/images/cleanerWelcomeImage.png"),
    successImage: require("../../assets/images/successImage.png"),
    hostProfile: require("../../assets/images/hostProfile.png"),
    visaCard: require("../../assets/images/visaCard.png"),
    masterCard: require("../../assets/images/masterCard.png"),
    americanEx: require("../../assets/images/americanEx.png"),
    googlePay: require("../../assets/images/googlePay.png"),
    applePay: require("../../assets/images/applePay.png"),
    cleanerPP: require("../../assets/images/cleanerPP.png"),
    cleanerPP1: require("../../assets/images/cleanerPP1.png"),
    hostPP: require("../../assets/images/hostPP.png"),
    hostPP1: require("../../assets/images/hostPP2.png"),
    apartment: require("../../assets/images/apartment.png"),
    apartment1: require("../../assets/images/apartment1.png"),
    apartment2: require("../../assets/images/apartment2.png"),
    apartment3: require("../../assets/images/apartment3.png"),
    apartment4: require("../../assets/images/apartment4.png"),
    apartment5: require("../../assets/images/apartment5.png"),
    apartment6: require("../../assets/images/apartment6.png"),
    apartment7: require("../../assets/images/apartment7.png"),
    emptyToDo: require("../../assets/images/emptyToDo.png"),
    recomendedEmpty: require("../../assets/images/recomendedEmpty.png"),
} as const;