export const FORM_FIELDS = {
    EMAIL: 'email',
    PASSWORD: 'password',
    NEW_PASSWORD: 'newPassword',
    CONFIRM_PASSWORD: "confirmPassword",
    CONFIRM_NEW_PASSWORD: "confirmNewPassword",
    OLD_PASSWORD: "oldPassword",
    FULL_NAME: 'fullName',
    USER_NAME: "userName",
    OTP: 'otp',
    CONTACT_NO: "phone",
    LOCATION: "location",
    TAX: "tax",
    DOCUMENTATION: "documentation",
    EXPERIENCE: "experience",
    SKILL: "skill",
    ADDRESS: 'address',
} as const;

export const FORM_LABELS = {
    [FORM_FIELDS.EMAIL]: 'Email Address',
    [FORM_FIELDS.PASSWORD]: 'Password',
    [FORM_FIELDS.NEW_PASSWORD]: "New Password",
    [FORM_FIELDS.CONFIRM_PASSWORD]: 'Confirm Password',
    [FORM_FIELDS.CONFIRM_NEW_PASSWORD]: 'Confirm New Password',
    [FORM_FIELDS.OLD_PASSWORD]: 'Old Password',
    [FORM_FIELDS.FULL_NAME]: 'Full Name',
    [FORM_FIELDS.USER_NAME]: "User Name",
    [FORM_FIELDS.CONTACT_NO]: "Contact Phone",
    [FORM_FIELDS.LOCATION]: "location",
    [FORM_FIELDS.TAX]: "Tax ID (Add your tax id for buying wholesaling products)",
    [FORM_FIELDS.DOCUMENTATION]: "Tax ID (Add your tax id for buying wholesaling products)",
    [FORM_FIELDS.EXPERIENCE]: "Years of Experience",
    [FORM_FIELDS.SKILL]: "Primary Bar Skills",
    [FORM_FIELDS.ADDRESS]: 'Address',
} as const;

export const FORM_PLACEHOLDERS = {
    [FORM_FIELDS.EMAIL]: 'Enter your email address',
    [FORM_FIELDS.PASSWORD]: 'Enter your password',
    [FORM_FIELDS.NEW_PASSWORD]: "Enter your New Password",
    [FORM_FIELDS.CONFIRM_PASSWORD]: "Enter your Confirm Password",
    [FORM_FIELDS.CONFIRM_NEW_PASSWORD]: "Confirm New Password",
    [FORM_FIELDS.OLD_PASSWORD]: "Enter Your Old Password",
    [FORM_FIELDS.FULL_NAME]: 'Enter your full name',
    [FORM_FIELDS.USER_NAME]: 'Enter your username',
    [FORM_FIELDS.CONTACT_NO]: "Enter your contact phone number",
    [FORM_FIELDS.LOCATION]: "New York, NY, USA .2 a...",
    [FORM_FIELDS.TAX]: "1485 482895632 86885938",
    [FORM_FIELDS.DOCUMENTATION]: "1485 482895632 86885938",
    [FORM_FIELDS.EXPERIENCE]: "Enter your Years of Experience",
    [FORM_FIELDS.SKILL]: "e.g., Mixology, Inventory, High-Volume",
} as const;